linters-settings:
  gci:
    sections:
      - standard
      - default
  lll:
    line-length: 120

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - gci
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofumpt
    - goheader
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - intrange
    - lll
    - makezero
    - mirror
    - misspell
    - nestif
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tagalign
    - tenv
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
